package internship_management_system.model;

import internship_management_system.enums.InternshipLevel;
import internship_management_system.filter.InternshipApplicationFilterSettings;
import internship_management_system.filter.InternshipOpportunityFilterSettings;
import internship_management_system.internships.InternshipApplication;
import internship_management_system.internships.InternshipOpportunity;
import internship_management_system.users.CareerCentreStaff;
import internship_management_system.users.CompanyRepresentative;
import internship_management_system.users.Student;
import internship_management_system.users.User;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Class to all data DataStorage will store all data types in static lists
 */
public class DataStorage {

    /**
     * Private constructor to prevent instantiation
     */
    private DataStorage() {
    }

    private static final List<Student> students = new ArrayList<>();
    private static final List<CompanyRepresentative> companyReps = new ArrayList<>();
    private static final List<CareerCentreStaff> careerCenterStaffs = new ArrayList<>();
    private static final List<InternshipOpportunity> internshipOpportunities = new ArrayList<>();
    private static final List<InternshipApplication> internshipApplications = new ArrayList<>();

    /**
     * Create a new Student and add to the list id is auto-incremented based on
     * list size
     *
     * @param userID the user ID of the student, used for login
     * @param name the name of the student
     * @param yearOfStudy the year of study of the student
     * @param major the major of the student
     * @param email the email of the student
     * @return the newly created Student object
     */
    public static Student newStudent(String userID, String name, int yearOfStudy, String major, String email) {
        Student s = new Student(students.size() + 1, userID, name, yearOfStudy, major, email);
        students.add(s);
        return s;
    }

    /**
     * Create a new Company Representative and add to the list id is
     * auto-incremented based on list size userID is autogenerated as "CR" + id
     *
     * @param name the name of the company representative
     * @param companyName the company name of the company representative
     * @param department the department of the company representative
     * @param position the position of the company representative
     * @return the newly created CompanyRepresentative object
     */
    public static CompanyRepresentative newCompanyRep(String name, String companyName, String department, String position, String email) {
        CompanyRepresentative c = new CompanyRepresentative(companyReps.size() + 1, name, companyName, department, position, email);
        companyReps.add(c);
        return c;
    }

    /**
     * Create a new Career Centre Staff and add to the list
     *
     * @param userID the user Id of the career centre staff, used for login
     * @param name the name of the career centre staff
     * @param department the department of the career centre staff
     * @param email the email of the career centre staff
     * @return the newly created CareerCentreStaff object
     */
    public static CareerCentreStaff newCareerCentreStaff(String userID, String name, String department, String email) {
        CareerCentreStaff c = new CareerCentreStaff(careerCenterStaffs.size() + 1, userID, name, department, email);
        careerCenterStaffs.add(c);
        return c;
    }

    /**
     * Create a new Internship Opportunity and add to the list
     *
     * @param title the title of the internship opportunity
     * @param description the description of the internship opportunity
     * @param preferredMajor the preferred major for the internship opportunity
     * @param level the level of the internship opportunity
     * @param openingDate the opening date of the internship opportunity
     * @param closingDate the closing date of the internship opportunity
     * @param companyRep the company representative for the internship
     * opportunity
     * @param numOfSlots the number of slots available for the internship
     * opportunity
     * @param visibility the visibility status of the internship opportunity
     * @return the newly created InternshipOpportunity object
     */
    public static InternshipOpportunity newInternshipOpportunity(String title, String description, String preferredMajor, InternshipLevel level, LocalDate openingDate, LocalDate closingDate, CompanyRepresentative companyRep, int numOfSlots, boolean visibility) {
        InternshipOpportunity i = new InternshipOpportunity(internshipOpportunities.size() + 1, title, description, preferredMajor, level, openingDate, closingDate, companyRep, numOfSlots, visibility);
        internshipOpportunities.add(i);
        return i;
    }

    /**
     * Create a new Internship Application and add to the list
     *
     * @param opportunity the internship opportunity for the application
     * @param student the student applying for the internship opportunity
     * @return the newly created InternshipApplication object
     */
    public static InternshipApplication newInternshipApplication(InternshipOpportunity opportunity, Student student) {
        InternshipApplication i = new InternshipApplication(internshipApplications.size() + 1, opportunity, student);
        internshipApplications.add(i);
        return i;
    }

    /**
     * Get a user (Student, CompanyRep, CareerCentreStaff) by their userID
     *
     * @param userID the user ID of the user to retrieve
     * @return an Optional containing the User if found, or an empty Optional if
     * not found
     */
    public static Optional<User> getUserByUserID(String userID) {
        for (Student s : students) {
            if (s.getUserID().equals(userID)) {
                return Optional.of(s);
            }
        }
        for (CompanyRepresentative c : companyReps) {
            if (c.getUserID().equals(userID)) {
                return Optional.of(c);
            }
        }
        for (CareerCentreStaff c : careerCenterStaffs) {
            if (c.getUserID().equals(userID)) {
                return Optional.of(c);
            }
        }
        return Optional.empty();
    }

    /**
     * @return the list of students
     */
    public static List<Student> getStudents() {
        return students;
    }

    /**
     * @return the list of company representatives
     */
    public static List<CompanyRepresentative> getCompanyReps() {
        return companyReps;
    }

    /**
     * @return the list of career centre staff
     */
    public static List<CareerCentreStaff> getCareerCentreStaffs() {
        return careerCenterStaffs;
    }

    /**
     * Get the list of internship opportunities
     * @return the list of all internship opportunities
     */
    public static List<InternshipOpportunity> getInternshipOpportunities() {
        return internshipOpportunities.stream()
                .filter(o -> !o.isDeleted())
                .toList();
    }

    /**
     * Get the list of internship opportunities matching the given filter settings
     * @param settings The filter settings to apply
     * @return the list of internship opportunities matching the filter
     */
    public static List<InternshipOpportunity> getInternshipOpportunities(InternshipOpportunityFilterSettings settings) {
        return internshipOpportunities.stream()
                .filter(o -> !o.isDeleted())
                .filter(o -> o.matchesFilter(settings))
                .toList();
    }
    
    /**
     * Get the list of internship applications
     * @return the list of all internship applications
     */
    public static List<InternshipApplication> getInternshipApplications() {
        return internshipApplications;
    }

    /**
     * Get the list of internship applications matching the given filter settings
     * @param settings The filter settings to apply
     * @return the list of internship applications matching the filter
     */
    public static List<InternshipApplication> getInternshipApplications(InternshipApplicationFilterSettings settings) {
        return internshipApplications.stream()
                .filter(a -> a.matchesFilter(settings))
                .toList();
    }

    /**
     * Get the list of internship applications for a given student
     * @param student The student whose applications to retrieve
     * @return the list of internship applications for the given student
     */
    public static List<InternshipApplication> getInternshipApplications(Student student) {
        return internshipApplications.stream()
                .filter(a -> a.getStudent().equals(student))
                .toList();
    }

    /**
     * Get the list of internship applications for a given opportunity  
     * @param opportunity The opportunity whose applications to retrieve
     * @return the list of internship applications for the given opportunity
     */
    public static List<InternshipApplication> getInternshipApplications(InternshipOpportunity opportunity) {
        return internshipApplications.stream()
                .filter(a -> a.getOpportunity().equals(opportunity))
                .toList();
    }

    /**
     * Get the list of internship applications for a given opportunity matching the given filter settings
     * @param opportunity The opportunity whose applications to retrieve
     * @param settings The filter settings to apply
     * @return the list of internship applications for the given opportunity matching the filter
     */
    public static List<InternshipApplication> getInternshipApplications(InternshipOpportunity opportunity, InternshipApplicationFilterSettings settings) {
        return internshipApplications.stream()
                .filter(a -> a.getOpportunity().equals(opportunity) && a.matchesFilter(settings))
                .toList();
    }


    /**
     * Get the internship application for a given opportunity and student
     * @param student The student who applied
     * @param settings The filter settings to apply
     * @return the list of internship applications matching the filter for the given student
     */
    public static List<InternshipApplication> getInternshipApplications(Student student, InternshipApplicationFilterSettings settings) {
        return internshipApplications.stream()
                .filter(a -> a.getStudent().equals(student) && a.matchesFilter(settings))
                .toList();
    }

    /**
     * Get the internship application for a given opportunity and student
     * @param opportunity The internship opportunity
     * @param student The student who applied
     * @return an Optional containing the internship application if found, or empty if not found
     */
    public static Optional<InternshipApplication> getInternshipApplicationForAnOpportunity(InternshipOpportunity opportunity, Student student) {
        for (InternshipApplication application : internshipApplications) {
            if (application.getOpportunity().equals(opportunity) && application.getStudent().equals(student)) {
                return Optional.of(application);
            }
        }
        return Optional.empty();
    }
}
